### ISSUE TITLE
Pull to refresh is broken

### ISSUE THREAD

**Issue by gmarty** [etiennesegonzac/snappy-twitter#5]
It looks like the latest update broke the pull to refresh gesture.

I need to kill the app and reopen to get new tweets.

**Comment by etiennesegonzac** [comment]
Strange, I've been using it non-stop.

You pull down, wait for the 'arrow' to rotate, release. And it should reload the current pane.
If it's not I'd love to see if there's anything in the log...

**Comment by etiennesegonzac** [comment]
Fixed in https://github.com/etiennesegonzac/snappy-twitter/commit/cf125e2c4c207c9827b3a2e34b203b0d12e2cd14
