### ISSUE TITLE
Pull-to-refresh doesn't actually refresh

### ISSUE THREAD

**Issue by Cwiiis** [etiennesegonzac/snappy-twitter#6]
Like the title says, seems if you pull to refresh, '...' is displayed for a couple of seconds, but no actual refresh takes place. Disabling the add-on restores the feature (which is terribly janky, but does actually refresh).

**Comment by etiennesegonzac** [comment]
The hackerplace doesn't support updates. But are you running the current master?
Anything in the logcat?
@Cwiiis

**Comment by gmarty** [comment]
I confirmed this bug on the latest version. I thought the previous update fixed it, but it only fixed the '...' change on the title.

**Comment by etiennesegonzac** [comment]
found it

**Comment by etiennesegonzac** [comment]
it's stupid :) Sorry about that, making a fix right now.

Thanks for beta testing!

**Comment by etiennesegonzac** [comment]
Should be fixed. I'll leave the issue open until one of you guys confirms it is.

**Comment by etiennesegonzac** [comment]
@gmarty just confirmed, cheers!
